### ISSUE TITLE
CI without installing g++ 

### ISSUE THREAD

**Issue by samibenelhajsalah** [samibenelhajsalah/continuous_integration#1]
- [ ] try with the cache
```yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        cpp-version: '11'  # Version de C++ souhaitée

    - name: Build project
      run: g++ -o myapp main.cpp

    - name: Run tests
      run: ./myapp
```
Effectivement, il est préférable d'éviter d'installer g++ à chaque exécution du workflow CI, car cela peut entraîner des déploiements plus lents et répétitifs. Une approche plus efficace consiste à installer les dépendances requises une seule fois, puis à les conserver dans le cache pour les utilisations ultérieures du workflow.

Voici un exemple de workflow CI avec GitHub Actions où les dépendances, y compris g++, sont installées une seule fois et ensuite conservées dans le cache :

Dans cet exemple, nous utilisons l'action actions/setup-cpp pour configurer l'environnement C++. L'action installe le compilateur g++ et d'autres dépendances nécessaires pour le développement C++.

Lors de l'exécution initiale du workflow, les dépendances seront installées et conservées dans le cache. Lors des exécutions ultérieures du workflow, les dépendances seront récupérées à partir du cache, ce qui réduira considérablement le temps d'exécution du workflow.

Cela permet de minimiser les installations répétées et de rendre le processus de construction plus efficace. Vous pouvez également personnaliser davantage ce workflow en ajoutant d'autres étapes comme des tests supplémentaires, des déploiements, etc.

N'hésitez pas à adapter le workflow en fonction des besoins spécifiques de votre projet.
